services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    # ports:
    #   - "9090:9090"
    # If you prefer to reach 127.0.0.1:5054/9001 directly, uncomment:
    network_mode: host

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: changeme
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # (optional) Seed dashboards/provisioning:
      # - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  prom_data:
  grafana_data:
